# ruff: noqa: E501
"""Self-contained HTML reporting for discovered DreamerV3 runs."""

from __future__ import annotations

import base64
import html
import json
from pathlib import Path
from typing import Any

import yaml

from dreamer_tools.bundle import BundleInfo, inspect_bundle
from dreamer_tools.model import Discovery, Severity


def write_report(
    run: Discovery,
    output: Path,
    *,
    bundle: Path | None = None,
    videos: tuple[Path, ...] = (),
) -> None:
    """Write a portable report containing no external scripts or styles."""
    metrics = _read_metrics(run.metrics_path)
    bundle_info = inspect_bundle(bundle) if bundle else None
    document = _render(run, metrics, bundle_info, videos)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(document, encoding="utf-8")


def _read_metrics(path: Path | None, limit: int = 2000) -> list[dict[str, Any]]:
    if not path:
        return []
    rows: list[dict[str, Any]] = []
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            value = json.loads(line)
            if isinstance(value, dict):
                rows.append(value)
    except (OSError, UnicodeError, json.JSONDecodeError):
        return []
    if len(rows) <= limit:
        return rows
    stride = max(1, len(rows) // limit)
    sampled = rows[::stride][: limit - 1]
    return [*sampled, rows[-1]]


def _render(
    run: Discovery,
    metrics: list[dict[str, Any]],
    bundle: BundleInfo | None,
    videos: tuple[Path, ...],
) -> str:
    status = {
        Severity.INFO: "Ready for structural inspection",
        Severity.WARNING: "Incomplete provenance",
        Severity.ERROR: "Run incomplete",
    }[run.severity]
    diagnostics = "".join(
        f'<li class="sev-{item.severity.name.lower()}"><span>{_symbol(item.severity)}</span> '
        f"{html.escape(item.message)}"
        f"{f'<small>{html.escape(item.action)}</small>' if item.action else ''}</li>"
        for item in run.diagnostics
    )
    cards = _summary_cards(run)
    charts = _charts(metrics)
    artifacts = _artifacts(bundle, videos)
    config = html.escape(
        yaml.safe_dump(run.config or {}, sort_keys=False, allow_unicode=True)
    )
    root = html.escape(str(run.root))
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Dreamer run report</title><style>{_STYLE}</style></head>
<body><main><header><p class="eyebrow">DREAMER WORLD MODEL</p>
<h1>Run report</h1><p class="path">{root}</p>
<div class="status sev-{run.severity.name.lower()}">{html.escape(status)}</div></header>
<section class="cards">{cards}</section>
<section><h2>Doctor</h2><ul class="diagnostics">{diagnostics}</ul></section>
<section><h2>Metrics</h2>{charts or '<p class="muted">No readable numeric metrics.</p>'}</section>
{artifacts}
<section><details><summary>Resolved configuration</summary><pre>{config}</pre></details></section>
<footer>Generated by dreamer-tools. Structural findings do not prove checkpoint compatibility.</footer>
</main></body></html>"""


def _summary_cards(run: Discovery) -> str:
    config = run.config or {}
    latest = run.latest_metrics or {}
    values = (
        ("Task", config.get("task")),
        ("Seed", config.get("seed")),
        ("Model", run.model_preset),
        ("Recorded step", latest.get("step")),
        ("Upstream", run.upstream_commit[:12] if run.upstream_commit else None),
        ("Checkpoint", _relative(run.checkpoint, run.root)),
    )
    return "".join(
        f"<article><span>{html.escape(label)}</span><strong>{html.escape(str(value)) if value is not None else 'Unknown'}</strong></article>"
        for label, value in values
    )


def _charts(rows: list[dict[str, Any]]) -> str:
    keys = sorted(
        {
            key
            for row in rows
            for key, value in row.items()
            if key != "step"
            and isinstance(value, (int, float))
            and not isinstance(value, bool)
        }
    )[:12]
    rendered = []
    for key in keys:
        points = [
            float(row[key]) for row in rows if isinstance(row.get(key), (int, float))
        ]
        if not points:
            continue
        rendered.append(
            f'<article class="chart"><h3>{html.escape(key)}</h3>{_sparkline(points)}'
            f"<p>{points[-1]:.5g} <small>latest</small></p></article>"
        )
    return f'<div class="charts">{"".join(rendered)}</div>' if rendered else ""


def _sparkline(values: list[float]) -> str:
    low, high = min(values), max(values)
    scale = high - low or 1.0
    count = max(1, len(values) - 1)
    points = " ".join(
        f"{index * 240 / count:.1f},{58 - (value - low) * 52 / scale:.1f}"
        for index, value in enumerate(values)
    )
    return f'<svg viewBox="0 0 240 64" role="img"><polyline points="{points}"/></svg>'


def _artifacts(bundle: BundleInfo | None, videos: tuple[Path, ...]) -> str:
    if not bundle and not videos:
        return ""
    parts = ["<section><h2>World-model artifacts</h2>"]
    if bundle:
        rows = "".join(
            f"<tr><td>{html.escape(key)}</td><td>{html.escape(str(shape))}</td>"
            f"<td>{html.escape(dtype)}</td></tr>"
            for key, (shape, dtype) in sorted(bundle.arrays.items())
        )
        parts.append(
            f"<h3>Extraction bundle</h3><p>{html.escape(bundle.path.name)}</p>"
            f"<table><thead><tr><th>Array</th><th>Shape</th><th>Dtype</th></tr></thead>"
            f"<tbody>{rows}</tbody></table>"
        )
    for video in videos:
        data = base64.b64encode(video.read_bytes()).decode("ascii")
        parts.append(
            f'<h3>{html.escape(video.stem)}</h3><video controls preload="metadata" '
            f'src="data:video/mp4;base64,{data}"></video>'
        )
    parts.append("</section>")
    return "".join(parts)


def _relative(path: Path | None, root: Path) -> str | None:
    return path.relative_to(root).as_posix() if path else None


def _symbol(severity: Severity) -> str:
    return {Severity.INFO: "✓", Severity.WARNING: "?", Severity.ERROR: "✗"}[severity]


_STYLE = """
:root{color-scheme:dark;--bg:#0b1020;--panel:#151c30;--ink:#eef2ff;--muted:#93a4c7;--line:#2a3655;--accent:#79e2c0;--warn:#ffd166;--error:#ff6b7a}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#172443,var(--bg) 40%);color:var(--ink);font:15px/1.55 ui-sans-serif,system-ui,sans-serif}main{width:min(1080px,calc(100% - 32px));margin:0 auto;padding:64px 0}header{margin-bottom:32px}.eyebrow{color:var(--accent);font-weight:800;letter-spacing:.18em}.path,.muted,footer{color:var(--muted)}h1{font-size:clamp(38px,7vw,72px);line-height:1;margin:.15em 0}.status{display:inline-block;padding:7px 12px;border:1px solid var(--line);border-radius:999px}.cards,.charts{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.cards article,.chart,section{background:color-mix(in srgb,var(--panel) 92%,transparent);border:1px solid var(--line);border-radius:14px;padding:20px}.cards article span,.cards article strong{display:block}.cards article span,small{color:var(--muted)}.cards article strong{font-size:18px;margin-top:6px;overflow-wrap:anywhere}section{margin:16px 0}section .cards{background:none;border:0}.diagnostics{padding:0;list-style:none}.diagnostics li{padding:9px 0;border-bottom:1px solid var(--line)}.diagnostics li span{display:inline-block;width:24px;font-weight:800}.diagnostics small{display:block;margin-left:28px}.sev-info{color:var(--accent)}.sev-warning{color:var(--warn)}.sev-error{color:var(--error)}.chart h3{font-size:14px;overflow-wrap:anywhere}.chart svg{width:100%;height:80px}.chart polyline{fill:none;stroke:var(--accent);stroke-width:2;vector-effect:non-scaling-stroke}.chart p{font-size:22px;margin:0}details summary{cursor:pointer;font-weight:700}pre{overflow:auto;color:#cad5f0;background:#080c17;padding:16px;border-radius:8px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid var(--line)}video{display:block;width:100%;max-height:640px;background:#000;border-radius:8px}footer{padding:32px 4px;text-align:center}
"""
